import type { Lead, LeadNote, LeadStatusChange, AIAnalysis } from './database.types';

// Mock data for development — demonstrates how the dashboard looks with real data
const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();

const defaultTrackingFields = {
  utm_term: null,
  utm_content: null,
  referrer_url: null,
  landing_page: null,
  device_type: null,
  ip_address: null,
  postcode: null,
  is_duplicate: false,
} as const;

export const mockLeads: Lead[] = [
  {
    id: '1',
    organization_id: 'org-1',
    first_name: 'Sarah',
    last_name: 'Mitchell',
    email: 'sarah.mitchell@gmail.com',
    phone: '0412 345 678',
    company: null,
    service_type: 'new_project',
    project_type: 'lighting',
    location: 'Bondi, Sydney',
    budget_range: '5k_15k',
    urgency: 'within_week',
    timeframe: null,
    message: 'Looking to upgrade all lighting in our 3-bedroom house to LED downlights. Also need some outdoor garden lighting installed. Would love a quote ASAP.',
    source: 'website',
    source_url: 'https://example.com/services/electrical',
    utm_source: 'google',
    utm_medium: 'cpc',
    utm_campaign: 'electrical-sydney',
    ...defaultTrackingFields,
    postcode: '2026',
    status: 'new',
    priority: 'high',
    custom_fields: {},
    ai_summary: 'High-intent residential lighting upgrade in Bondi. Budget $5-15k, wants response within a week. Phone provided — recommend calling within 1 hour.',
    ai_priority: 'high',
    ai_score: 82,
    ai_recommended_action: 'Call within 1 hour — strong conversion potential',
    won_value: null,
    won_date: null,
    assigned_to: null,
    last_contacted_at: null,
    follow_up_date: null,
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
  },
  {
    id: '2',
    organization_id: 'org-1',
    first_name: 'James',
    last_name: 'Chen',
    email: 'james.chen@outlook.com',
    phone: '0423 456 789',
    company: 'Chen Property Group',
    service_type: 'maintenance',
    project_type: 'switchboard',
    location: 'Surry Hills, Sydney',
    budget_range: '15k_50k',
    urgency: 'asap',
    timeframe: null,
    message: 'Urgent: switchboard upgrade needed for a commercial property. Current board is old and tripping frequently. Need certified electrician for compliance.',
    source: 'website',
    source_url: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    ...defaultTrackingFields,
    postcode: '2010',
    status: 'contacted',
    priority: 'critical',
    custom_fields: {},
    ai_summary: 'URGENT commercial switchboard upgrade. Compliance-driven, high budget ($15-50k). Company lead — likely repeat business potential. Immediate call recommended.',
    ai_priority: 'critical',
    ai_score: 95,
    ai_recommended_action: 'Call immediately — emergency commercial job, high value',
    won_value: null,
    won_date: null,
    assigned_to: null,
    last_contacted_at: hoursAgo(1),
    follow_up_date: null,
    created_at: hoursAgo(5),
    updated_at: hoursAgo(1),
  },
  {
    id: '3',
    organization_id: 'org-1',
    first_name: 'Emily',
    last_name: 'Watson',
    email: 'emily.w@yahoo.com',
    phone: null,
    company: null,
    service_type: 'consultation',
    project_type: null,
    location: 'Manly',
    budget_range: 'unsure',
    urgency: 'no_rush',
    timeframe: null,
    message: 'Just exploring options for solar panel installation. Not urgent.',
    source: 'website',
    source_url: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    ...defaultTrackingFields,
    status: 'reviewed',
    priority: 'low',
    custom_fields: {},
    ai_summary: 'Early-stage solar enquiry. No phone, unsure budget, no rush. Low priority — respond via email within 48 hours.',
    ai_priority: 'low',
    ai_score: 35,
    ai_recommended_action: 'Send email with solar info pack within 48 hours',
    won_value: null,
    won_date: null,
    assigned_to: null,
    last_contacted_at: null,
    follow_up_date: null,
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: '4',
    organization_id: 'org-1',
    first_name: 'Michael',
    last_name: 'Torres',
    email: 'mtorres@build.com.au',
    phone: '0434 567 890',
    company: 'Torres Developments',
    service_type: 'new_project',
    project_type: 'ev_charger',
    location: 'Coogee, Sydney',
    budget_range: '1k_5k',
    urgency: 'within_month',
    timeframe: null,
    message: 'Need 2x Tesla Wall Connector chargers installed at a residential development. 6 units total.',
    source: 'referral',
    source_url: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    ...defaultTrackingFields,
    status: 'quote_sent',
    priority: 'medium',
    custom_fields: {},
    ai_summary: 'Multi-unit EV charger installation in Coogee. Developer — potential for ongoing work. Budget modest per unit but 6 units total.',
    ai_priority: 'medium',
    ai_score: 68,
    ai_recommended_action: 'Follow up on quote within 2 business days',
    won_value: null,
    won_date: null,
    assigned_to: null,
    last_contacted_at: daysAgo(2),
    follow_up_date: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
  {
    id: '5',
    organization_id: 'org-1',
    first_name: 'Lisa',
    last_name: 'Nguyen',
    email: 'lisa.nguyen@gmail.com',
    phone: '0445 678 901',
    company: null,
    service_type: 'renovation',
    project_type: 'power_wiring',
    location: 'Newtown, Sydney',
    budget_range: '5k_15k',
    urgency: 'within_week',
    timeframe: null,
    message: 'Full rewiring of our terrace house before renovation starts next month. Need quote urgently.',
    source: 'website',
    source_url: null,
    utm_source: 'google',
    utm_medium: 'organic',
    utm_campaign: null,
    ...defaultTrackingFields,
    postcode: '2042',
    status: 'new',
    priority: 'high',
    custom_fields: {},
    ai_summary: 'Urgent full rewire for terrace house renovation in Newtown. Time-sensitive — renovation starts next month. Good budget range.',
    ai_priority: 'high',
    ai_score: 78,
    ai_recommended_action: 'Call within 2 hours — time-sensitive renovation project',
    won_value: null,
    won_date: null,
    assigned_to: null,
    last_contacted_at: null,
    follow_up_date: null,
    created_at: hoursAgo(8),
    updated_at: hoursAgo(8),
  },
  {
    id: '6',
    organization_id: 'org-1',
    first_name: 'David',
    last_name: 'Kowalski',
    email: 'david.k@hotmail.com',
    phone: '0456 789 012',
    company: null,
    service_type: 'maintenance',
    project_type: 'smoke_alarms',
    location: 'Randwick',
    budget_range: 'under_1k',
    urgency: 'flexible',
    timeframe: null,
    message: 'Need smoke alarms replaced in rental property for compliance.',
    source: 'website',
    source_url: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    ...defaultTrackingFields,
    status: 'won',
    priority: 'low',
    custom_fields: {},
    ai_summary: 'Small compliance job — smoke alarm replacement in rental. Low value but quick turnaround.',
    ai_priority: 'low',
    ai_score: 45,
    ai_recommended_action: 'Schedule at next available slot',
    won_value: null,
    won_date: null,
    assigned_to: null,
    last_contacted_at: daysAgo(4),
    follow_up_date: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(2),
  },
  {
    id: '7',
    organization_id: 'org-1',
    first_name: 'Rachel',
    last_name: 'Simmons',
    email: 'rachel@simmonslaw.com.au',
    phone: '0467 890 123',
    company: 'Simmons & Associates',
    service_type: 'new_project',
    project_type: 'lighting',
    location: 'CBD, Sydney',
    budget_range: '15k_50k',
    urgency: 'within_month',
    timeframe: null,
    message: 'Fit-out for new law office in the CBD. Need premium lighting design and installation. 200sqm space.',
    source: 'referral',
    source_url: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    ...defaultTrackingFields,
    status: 'contacted',
    priority: 'high',
    custom_fields: {},
    ai_summary: 'Premium commercial lighting fit-out for law firm in CBD. High value ($15-50k), professional client. Strong conversion potential.',
    ai_priority: 'high',
    ai_score: 88,
    ai_recommended_action: 'Schedule site visit this week',
    won_value: null,
    won_date: null,
    assigned_to: null,
    last_contacted_at: daysAgo(1),
    follow_up_date: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: '8',
    organization_id: 'org-1',
    first_name: 'Tom',
    last_name: 'Bradley',
    email: 'tom.bradley@outlook.com',
    phone: null,
    company: null,
    service_type: 'consultation',
    project_type: 'inspection',
    location: 'Parramatta',
    budget_range: null,
    urgency: 'no_rush',
    timeframe: null,
    message: null,
    source: 'website',
    source_url: null,
    utm_source: null,
    utm_medium: null,
    utm_campaign: null,
    ...defaultTrackingFields,
    status: 'lost',
    priority: 'low',
    custom_fields: {},
    ai_summary: 'Minimal information provided. No phone, no budget, no message. Very low intent signal.',
    ai_priority: 'low',
    ai_score: 15,
    ai_recommended_action: 'Low priority — send standard email if time permits',
    won_value: null,
    won_date: null,
    assigned_to: null,
    last_contacted_at: daysAgo(6),
    follow_up_date: null,
    created_at: daysAgo(7),
    updated_at: daysAgo(5),
  },
];

export const mockNotes: LeadNote[] = [
  { id: 'n1', lead_id: '2', user_id: null, content: 'Called James — confirmed switchboard is original from 1985. Needs full upgrade with compliance certificate. Sending quote today.', is_system: false, created_at: hoursAgo(1) },
  { id: 'n2', lead_id: '2', user_id: null, content: 'Lead automatically qualified as CRITICAL by AI', is_system: true, created_at: hoursAgo(5) },
  { id: 'n3', lead_id: '7', user_id: null, content: 'Spoke with Rachel. Very professional, clear brief. Site visit booked for Thursday.', is_system: false, created_at: daysAgo(1) },
  { id: 'n4', lead_id: '4', user_id: null, content: 'Quote sent for $8,400 for 6 units. Waiting on developer approval.', is_system: false, created_at: daysAgo(1) },
];

export const mockStatusChanges: LeadStatusChange[] = [
  { id: 'sc1', lead_id: '2', user_id: null, from_status: 'new', to_status: 'reviewed', created_at: hoursAgo(4) },
  { id: 'sc2', lead_id: '2', user_id: null, from_status: 'reviewed', to_status: 'contacted', created_at: hoursAgo(1) },
  { id: 'sc3', lead_id: '7', user_id: null, from_status: 'new', to_status: 'contacted', created_at: daysAgo(1) },
  { id: 'sc4', lead_id: '4', user_id: null, from_status: 'contacted', to_status: 'quote_sent', created_at: daysAgo(1) },
  { id: 'sc5', lead_id: '6', user_id: null, from_status: 'quote_sent', to_status: 'won', created_at: daysAgo(2) },
];

export function getMockLeadWithRelations(leadId: string) {
  const lead = mockLeads.find((l) => l.id === leadId);
  if (!lead) return null;
  return {
    ...lead,
    notes: mockNotes.filter((n) => n.lead_id === leadId),
    status_changes: mockStatusChanges.filter((sc) => sc.lead_id === leadId),
    tags: [],
    ai_analysis: null,
  };
}
